"use strict";

var mott = require('../index.js');

mott.config
    .file('config.json')
    .defaults({
        'BASE_URL':  'http://local-dev.ex.fm:3000"',
        'API_URL': 'http://ex.fm',
        'NODE_ENV': 'development',
        'WEINRE': null,
        'USE_GZIP': false,
        'MINIFY': false,
        'SOCKETIO': false,
        'EXPORT_CONFIG': [
            'BASE_URL',
            'API_URL',
            'NODE_ENV',
            'WEINRE'
        ],
        'VERSION': '3.0.0',
        'VERSION_CODE': 3000,
        'PLATFORMS': [
            'web',
            'iphone'
        ],
        'ASSETS': __dirname + '/assets',
        'WATCH_PATH': __dirname,
        'PORT': 3000,
        'SERVER': __dirname + '/server.js',
        'AUTOGENERATED_FILES': [
            'app.js',
            'app.css',
            'templates.js',
            'bootstrap.js',
            'config.js',
            'strings.js',
            'templates.js'
        ],
        'SMOKE_TEST': __dirname + '/test/smoke.js',
        'ALBUM_ART_URL': 'http://cdn.albumart.extension.fm',
        'IMAGE_URL': 'http://images.extension.fm',
        'AWS': {
            'KEY': '<your aws access key>',
            'SECRET': '<your aws secret>'
        }
    });

mott.connect();

module.exports = function(grunt){
    grunt.initConfig({});
    grunt.loadTasks('../tasks/');
    grunt.registerTask('default', 'build run');
};
