"use strict";

var nconf = require('nconf'),
    when = require('when'),
    common = require('./common'),
    hbs = require('hbs'),
    tpl = [
        '// this file is autogenerated.  Dont check it in.',
        'process.env = module.exports = {{{data}}};'
    ].join('\n');

module.exports = function generateConfig(platform){
    var d = when.defer(),
        data = {
            'PLATFORM': platform
        },
        template = hbs.handlebars.compile(tpl);

    nconf.get('EXPORT_CONFIG').forEach(function(key){
        data[key] = nconf.get(key);
    });

    return common.writeFile(nconf.get('ASSETS') + '/' + platform + '/js/config.js',
        template({'data': JSON.stringify(data, null, 4)}));
};